version: 2.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1        
    steps:
      - checkout
      - run: ./mvn clean install
      - persist_to_workspace:
         root: ./
         paths:
           - target/

  test:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvn test

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build